name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # 替换为你的默认分支名称

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd shiki_magic_move_widget_for_notion
          npm install

      - name: Build project
        run: |
          cd shiki_magic_move_widget_for_notion
          npm run build

      - name: Verify build output
        run: |
          cd shiki_magic_move_widget_for_notion
          if [ ! -d "./dist" ]; then
            echo "Error: Build output directory 'dist' does not exist."
            exit 1
          fi
          ls -la ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./shiki_magic_move_widget_for_notion/dist
